"""create_stage_1_tables

Revision ID: faafc5ad4477
Revises: 
Create Date: 2026-10-08 23:17:22.695374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types


# revision identifiers, used by Alembic.
revision: str = 'faafc5ad4477'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trust_level', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_sources_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_data_sources_id'), ['id'], unique=False)

    op.create_table('geographic_areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('area_type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('geometry', app.models.types.SafeGeometry(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['geographic_areas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geographic_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geographic_areas_area_type'), ['area_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_geographic_areas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_geographic_areas_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_geographic_areas_parent_id'), ['parent_id'], unique=False)

    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_categories_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_categories_id'), ['id'], unique=False)

    op.create_table('population_cells',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('geometry', app.models.types.SafeGeometry(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('demographics', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['geographic_areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('population_cells', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_population_cells_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_population_cells_id'), ['id'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geometry', app.models.types.SafeGeometry(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('operating_hours', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['geographic_areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_verification_status'), ['verification_status'], unique=False)

    op.create_table('community_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reporter_id', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geometry', app.models.types.SafeGeometry(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['geographic_areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_reports_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_reports_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_reports_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_reports_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_reports_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_reports_verification_status'), ['verification_status'], unique=False)

    op.create_table('service_capacities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_load', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_capacities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_capacities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_capacities_service_id'), ['service_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_capacities_status'), ['status'], unique=False)

    op.create_table('report_verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('verifier_id', sa.String(length=100), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verification_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['community_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_verifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_verifications_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_verifications_verifier_id'), ['verifier_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_verifications_verifier_id'))
        batch_op.drop_index(batch_op.f('ix_report_verifications_report_id'))
        batch_op.drop_index(batch_op.f('ix_report_verifications_id'))

    op.drop_table('report_verifications')
    with op.batch_alter_table('service_capacities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_capacities_status'))
        batch_op.drop_index(batch_op.f('ix_service_capacities_service_id'))
        batch_op.drop_index(batch_op.f('ix_service_capacities_id'))

    op.drop_table('service_capacities')
    with op.batch_alter_table('community_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_reports_verification_status'))
        batch_op.drop_index(batch_op.f('ix_community_reports_status'))
        batch_op.drop_index(batch_op.f('ix_community_reports_source_type'))
        batch_op.drop_index(batch_op.f('ix_community_reports_severity'))
        batch_op.drop_index(batch_op.f('ix_community_reports_service_id'))
        batch_op.drop_index(batch_op.f('ix_community_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_community_reports_id'))
        batch_op.drop_index(batch_op.f('ix_community_reports_category_id'))
        batch_op.drop_index(batch_op.f('ix_community_reports_area_id'))

    op.drop_table('community_reports')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_verification_status'))
        batch_op.drop_index(batch_op.f('ix_services_status'))
        batch_op.drop_index(batch_op.f('ix_services_source_type'))
        batch_op.drop_index(batch_op.f('ix_services_name'))
        batch_op.drop_index(batch_op.f('ix_services_id'))
        batch_op.drop_index(batch_op.f('ix_services_category_id'))
        batch_op.drop_index(batch_op.f('ix_services_area_id'))

    op.drop_table('services')
    with op.batch_alter_table('population_cells', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_population_cells_id'))
        batch_op.drop_index(batch_op.f('ix_population_cells_area_id'))

    op.drop_table('population_cells')
    with op.batch_alter_table('service_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_categories_id'))
        batch_op.drop_index(batch_op.f('ix_service_categories_code'))

    op.drop_table('service_categories')
    with op.batch_alter_table('geographic_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geographic_areas_parent_id'))
        batch_op.drop_index(batch_op.f('ix_geographic_areas_name'))
        batch_op.drop_index(batch_op.f('ix_geographic_areas_id'))
        batch_op.drop_index(batch_op.f('ix_geographic_areas_area_type'))

    op.drop_table('geographic_areas')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sources_id'))
        batch_op.drop_index(batch_op.f('ix_data_sources_code'))

    op.drop_table('data_sources')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
